# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader:
          include_format: false
    view:
          view_response_listener:  true
    serializer:
          serialize_null: true
    format_listener:
          rules:
               - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    zone:
        # Prototype
        - # use the urldecoded format
           path: ^/api # Example: ^/path to resource/
